version: '3.1'
services:
  mongo:
    image: mongo
    container_name: tickets-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'
  # auth:
  #   image: abner/auth
  #   container_name: tickets-auth
  #   ports:
  #     - '3000:3000'
